---
version: "3.5"
services:
  services-portal:
    image: "nginx:latest"
    restart: always
    ports:
      - 20000:80

    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./logs:/var/log/nginx"
      - "./dist:/usr/share/nginx/html"

volumes:
  data: